# Generated by Django 2.1.7 on 2019-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='image',
            field=models.ImageField(default='ptf/static/MIT-Earth-Dish_0.jpg', upload_to='images/'),
        ),
    ]
