# Generated by Django 2.1.7 on 2019-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0002_presentations_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='link',
            field=models.CharField(default='"Attenuation_Bias_MCS.pdf"', max_length=255),
        ),
    ]
