# Generated by Django 2.1.7 on 2019-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0003_presentations_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentations',
            name='text',
            field=models.TextField(default='NONE', max_length=255),
        ),
    ]
