# Generated by Django 2.1.7 on 2019-04-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0004_presentations_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentations',
            name='text',
            field=models.URLField(default='404'),
        ),
    ]
