# Generated by Django 2.1.7 on 2019-04-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0005_auto_20190425_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentations',
            name='text',
        ),
    ]
