# Generated by Django 2.1.7 on 2019-04-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentations', '0006_remove_presentations_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentations',
            name='link',
        ),
    ]
